name: Build ShakeShare APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Restore project files
        run: |
          rm -f /tmp/proj.b64
          echo 'H4sIAAAAAAAAA+w9a3faSLL57F/R4cxdw04QCLDJENsZjHHCrl/HOMnsmTuHI6QGOhaSVg/bjJOv' >> /tmp/proj.b64
          echo '9w/cf3h/ya1+SS0JsB3bZGaWnnPGqLu6+lHVVdXV1R2t8uLZUxVSc2uL/YWU/ct+61t6s9HU9eZW' >> /tmp/proj.b64
          echo 'A/KbzdrWC7T1/F178SIKQsNH6IXvuuEyuLvK/6RJq5iuhafGmJjazJjaz9EGJfB2o7GI/nq1riv0' >> /tmp/proj.b64
          echo '119U9dqW3niBqs/RmWz6D6f/tetfjmz3OmhtIGQ4lu8Sq+xjGxsBplkIOcYUt1B/Ylxi+J+PUfvs' >> /tmp/proj.b64
          echo 'n2g/IrbFiqfGzWBIvwZW5BshcZ0W2q6yIuxcEd91ptgJOSqERnYUhthvIZj1oY1F7mfjymghvck+' >> /tmp/proj.b64
          echo 'A9MnXhjIGmXRgXc4RIe8NvIM89IY40CAyDotiR550RCNcZhBwTqNxODoMBbWZwNChneJynIy4Jfj' >> /tmp/proj.b64
          echo 'lkMf43JA56JMTNfhPTD8kIwMU+0zQ1AxPK/iRqEXhUFFoC4DUpov0WrwzWpBl20STIgzllhgVRK7' >> /tmp/proj.b64
          echo 'FffRxybxCMxlkOTRpmZu5JcZ7M/4xph6NtZMdxqDOC50bqZWCSLTxEHQQqEfYSV/BCgiH4v8782Y' >> /tmp/proj.b64
          echo '67SSpFW0MQnJ2HF9/Fxt3CH/q7VaI63/4Y9eX8v/VSTNAuk1CF3XrmxoUkZ5djQmINyyGWULe9ix' >> /tmp/proj.b64
          echo 'sGMSEL4aiKyyaZgTXGG/Kxtc6m38XSNTe0MjFjag5CqgFkZlQyiXiu2ahq15vuthkJuARxZoY9+w' >> /tmp/proj.b64
          echo 'bID83nPyn5S0ipz+52vjQfb/9jZd//Wt6tr+X0VK6M8Wr1iDT9vGXfK/2qwr9K8D/evbtbX9v5JU' >> /tmp/proj.b64
          echo 'qaAL1yvb+ArbwuwdETAhUcd1RmQsTHpEHBTgMATrNBAsoq3F9F8hJeufblaep40Hyf8mtf9qeq25' >> /tmp/proj.b64
          echo 'lv+rSGn6P48OuEP+13Rd+n9qW9tNyNcbjaq+lv+rSMKyR7fMEUAsVDDdqSZ4QgOesInJVEAhBrh0' >> /tmp/proj.b64
          echo 'Q5s4ZQGT5Fv4Sm4Y4o0DZyWxfyhsfN2Q1r5okDpmAs8wMW+XeVYC6mWiTXPUkO+BRupbl6je2FCz' >> /tmp/proj.b64
          echo 'Tj3aMdl35tpwI9/EHSiGPg+JTcIZ+odxZXzEfgCg2sfueb93ejLQB6/jOkD+MQ7vX+cr7wOfhXwX' >> /tmp/proj.b64
          echo 'Pl9NLxhGtIsKuva6oFbi/evjUK0xNYijUReYFvjmAfED9CNUhd8VWlLhDaXQWHhkRHbIVbSCSSFX' >> /tmp/proj.b64
          echo 'z1o8o6xR4tAZremZeRDTLDOv+CR0YAeH9GzuCRCPjrGqVRXE0DFygG+6DnXwWYmTSfSdiZiLmYfV' >> /tmp/proj.b64
          echo 'KZA+tlvFHQWzRcYOWBximKmvQLPwMBqnwGFIZDST7Y4MO8BpdBOfOJfnmBMhyEB8VTvJHYzQWp6+' >> /tmp/proj.b64
          echo '+Ma0I5iNwnH3ol3unRxWDrpn3ZOD7kmn1+0XlsAd9Trdk353GcjJ6QUASVpDZ6RD8lZhH1TQtIqm' >> /tmp/proj.b64
          echo 'sdWkbsjlGqYuQOpz5ZZbwfXH2mccDn1gpkDj3NQSazgILZsMy5+ty2ZL136SdMyiEGv2RmPEtfBN' >> /tmp/proj.b64
          echo 'K/5RA+rrtCvfW5Ct0zeltP6nQufp23iQ/VdvUvuvqa/P/1aS8vRnSudJ23gA/WsAyfb/9bX/ZyVp' >> /tmp/proj.b64
          echo 'Af25fngiNnj4+t/SG/qa/qtIy+kPFuQT8MA30L+pr/f/K0l30z/ZQXwrKzyY/qAF6mv9v5L0IPp/' >> /tmp/proj.b64
          echo 'o4vwQfpfr1H6b1fX+n8l6cH0P4bithmSKxLOtMt7TQkl8LLzHz05/xH0r281amv/3yqSCKVCeV/R' >> /tmp/proj.b64
          echo 'xgaZeq4fIuLGbj08HWLLIs449hCKkCzJERsbpm0EAVK5pIUyQMUSul17DP4YacH693HwdHvAh9t/' >> /tmp/proj.b64
          echo 'jUa9tpb/q0hL6H9l2NGTsMGD9H+tyu3/+pr+q0h30z8IfXbsf/PNweF36v9t1f7bovYfO/9d6//n' >> /tmp/proj.b64
          echo 'Tztvga7yQGeXHuYUEHZMlyr53UIUjsqvC2/3NnZ8eWyyx04IdjhXsPO73QKwzoD+KuwlYeI7gnGg' >> /tmp/proj.b64
          echo 'bkWp/L3Hu07pdJ/1P7PxY5b/net/G2z+tPxvNrfW638l6dvXP3CFWP5HRuSYk4sJBgmAPFj7Trhb' >> /tmp/proj.b64
          echo '+FnwVYtBVliptm/DdkM7cS9IaON9wy/sxYehOyTEUylPRNVr4lju9T7UGftu5FiFvRir6dquXxlS' >> /tmp/proj.b64
          echo 'fDsVWlX0i7PrnE6euP7UsP9YnfwDSMYF67/NM48Nh4xwED5m9d+5/rf0Wi1z/tNs1NbxPytJO1NB' >> /tmp/proj.b64
          echo 'YgQkdoKW4IbdwiQMvValEpiwJowg3u9TjxC9wkQVhIwA2uNBEzsvy2W0DzojhKmaoKKNx4Y5Q+2z' >> /tmp/proj.b64
          echo 'HtpBdb2EymXB/1GAg7KH/SkJqNiR985aqYWlJQDa/tGH7sXp6cX7JHhC1pkaN33r8qMUYHWQX5VH' >> /tmp/proj.b64
          echo 'NzNoHxz3Tu7b2NzR02HX9R+fZNSDfqc9pzcU4VkMfmgb42C34GAQ5oeuf+SKuK2nmY6P3fOLXr/7' >> /tmp/proj.b64
          echo 'JNg6pycn3c5FZu4+kUPyiMlqdzrdfn/wqXfYG/Qv2heP6WrnffvkXfdpcJ102+f7/+K4Drofex01' >> /tmp/proj.b64
          echo 'SOjhlEzmS2ajoo//HRGfxjy5PjrBhj+c0fBtB5sseOkxLChm9bB30h0cnXbaF73Tk0dMhkDXOW2f' >> /tmp/proj.b64
          echo '9zMIk4H1Q9enLskKOsYWMR7R+/Nu+2DQ/eWie37SPgJKnp6333XvXtW1R4zw03nvovvwNmuvH9Em' >> /tmp/proj.b64
          echo 'G+Zx96DXHvSOobW+MqFKSGCuD7YxxPZuIdmz5bvJ2/zhVkFDo/6+5iHpdVgwqKbEmxpehZgDm1mF' >> /tmp/proj.b64
          echo '2M+DUn4FjXPE9EP3JsS+Y9iC6rsFGjComlyGdC0jJaX7p6nu5sJcQHxDfdnYEvjnwvAeH7sWoAzA' >> /tmp/proj.b64
          echo '/rXxhevNBw2ppQjD5XajagDPBTdZ0GJnYjhjDCvb9YkMrvtyiWdD1/Ct98SycPL5JTB9jJ0++R1/' >> /tmp/proj.b64
          echo 'CcBwhS1Y2E+y2CU6+GPM3Cg8gMXPlvqXkesAFC3h1Y9Y+RdAHMDMfIkIHdz8LgL9rWvggbZpYhv7' >> /tmp/proj.b64
          echo 'xh1zxa3evjsKe44XhXzSDOszmFPnOIAuKiRkZJzi0ChbRmiksvO0XHraoBrxC/FImzomT8r0r2T6' >> /tmp/proj.b64
          echo 'RZwQaFEeERua3MshZey3cBHyyhqH0Y7bvZNcAwwJrBw8dv3ZcjQSSjtqfzjpvO+e53tbWdDdnYpc' >> /tmp/proj.b64
          echo 'Jkre/ClPd0HMdVdO9XxqM1cASKlESFUUiUA3MtKMXHt4/lwp2f+Ja13Jxdwna+NO/6/ezNz/bDRr' >> /tmp/proj.b64
          echo '6/vfK0k0OlxQ/vPV1PDB8Cz/Mr1pvJMXNTQwR4Q34JddFswvCzCLtP8HDsmIYH93/WrEnzFl1/9z' >> /tmp/proj.b64
          echo 'XAF8+PlvbbvaWJ//rSLl6H/tg2bH/lPywYPo32Tn/7XmOv5rJWkh/cXNPfH5KLPgLv1f1zP0r+n1' >> /tmp/proj.b64
          echo '9ftfq0kWoce0w4ja8ftGgHffnbcPjrqDD/3u+eD96XF3Q4U4M8LJruQQWhBs/E48unXH8yvL0jkV' >> /tmp/proj.b64
          echo 'VbwffHuXOpyD/6YuZ+xfERPHDw2AiVJRgQPJm6+1ahl2xho0sjY8vjEl6z/zvsMTtnHH+tfrdfX9' >> /tmp/proj.b64
          echo 'F/r+X6O+XV2v/1UkfjP72HCMMbvxKS6RWngkH8PrW5d09aJd5RIsLU40AhQ5+BqdxRnFUgxJHxMp' >> /tmp/proj.b64
          echo 'FrJvPhVK2jUJJ8x11A99bEzRrYJQs13DKpKwJG7lLuyRUmWMQ9GBWVF6NbTAuiwkfTECEC1hFstL' >> /tmp/proj.b64
          echo '6H1k26+QWos+m0dfPKEPn+Q6r1xbDiPfySDkl3dhCvhVWofd8WVPDxYLP9ymYb9W5FOG8n1A9hSX' >> /tmp/proj.b64
          echo 'lHAFgcTHnhuQkLoN1avIY9cdw+wmA5waV9jpABV9w1ayObIzRukz1w/jQnbFOP8CwLyL/ByqTAmD' >> /tmp/proj.b64
          echo '/YIMGEjd/l72eEBS4bWma40Cu6o+U65g08rzbipLbKkm6UXlFAYYhphoVGixe+7fe139WZJWscnw' >> /tmp/proj.b64
          echo 'md8AfoD9X6vWafxPtbG1vv+1ksTpD0uGPQT4PG3cpf+3cvSv6dV1/NdKkrjjsSn0UEvI+8rUgP8T' >> /tmp/proj.b64
          echo '0HuULTbfbGThuO4Z0AMn0FbKR7YCP4gKKhN3igf8Q4KIuyLJ+WPb8xC+CbFjQW4IPbBxEHwiFn1N' >> /tmp/proj.b64
          echo 'haon+uJumIYv3gYR3Z9e4tnX0huqLn92QVP4xKJ6RdRlb44UmQ7uQB+hCYqK/i0JtSc0+bEYNUUs' >> /tmp/proj.b64
          echo '1GdIo8BaaDNpdfPVhjRJhtG4P3GvOxNsXmKLHoLtG45D3zdmekkCstPCFmInUAdGaBRj1Tz0yXgS' >> /tmp/proj.b64
          echo 'Ouw53v34N52gy1cxUGAao5FrW0mMWYcGlrXEfLCPYvXm8LDK/islNVkAWt/kzXeSD23ku9M+xlZR' >> /tmp/proj.b64
          echo 'Oe4J4HsB4sOfmnV9W0F8z56XNNP1Zp/A1Es1FPkjw8T5ZvQ2/U9pRvlJqXXBB/KOsdsh4zbP9Tyw' >> /tmp/proj.b64
          echo 'Fi5kaTGeZNaVYkmLKyrIogBLUtf5e8eyLAai/Cp7+B5+88PXoigHVuPm0/dev49NXP7LLffzGAIP' >> /tmp/proj.b64
          echo '0v9b9PynVtfX939WkjL0Z1cAB+LzqUyCO/f/zaai/yn9t6tr/b+aJNU0JXXLCGaOqehulgmWwGSO' >> /tmp/proj.b64
          echo 'ARCAUnf9YAAbQ2Ab5WOuducMxZRtQANfTCFZLTca2hgNwomPgwnoONjU6w2t+iYLSJwQDUDhgvYz' >> /tmp/proj.b64
          echo '8TF1OfxUrTJ9z/0H/WjIH/GHLeKOiGEBqU1DG2BPHO69RYMgGlK0oBvwBZliyIEOhqx/DNEVfZaO' >> /tmp/proj.b64
          echo 'ckNYZD8PoSmKrlhCrsPApLVAUUEPjFwzvC/FgD7DT5zxGWgY12qhPpueHlgc/hWYVBGRP0uaTQKw' >> /tmp/proj.b64
          echo 'd4rFGDd1mTiGDXv5MTQR/Bt6g7Ub9HdE//8j/H/Gfs/Y79/Z79+ZNmK76BEq0op7yoyWFI8BR+24' >> /tmp/proj.b64
          echo '14BazoMGn8UYA8eRzAza5e4R9OVLKjIEKmkWGY2wj4EgSoWXJY04x8SGgWEgHVhyeyrhSqk33tR2' >> /tmp/proj.b64
          echo 'KMo3SpmYc7Vr0hsk3moTSjghnesVVRK91UwDGrUlCkE2Opy/ivp+dMrIf4dFjz6xAlgu/3W9VtMz' >> /tmp/proj.b64
          echo '+n9b317Hf6wkpUR9OPOwNaARY3MEvmANMwksruSzMsL/AFM26jkjly1LLn76/Oog7PI8F8R6z3qT' >> /tmp/proj.b64
          echo 'LaKhaW/i/V6CpHgbhzqHExJoCYpXKF1CMVD5ANIBO9FUREWzPSW6RcSy8SvY7xi+Sf/BlVdIjAAD' >> /tmp/proj.b64
          echo 'ntA3nGBEd5C0wHIdgIQv16eSho9KIMvrND6IdPGAgMhJZWkDLpDoPxlDYwJThSDAdkFgEgowp1ZW' >> /tmp/proj.b64
          echo 'LYoJkwu2R/XnZv4th82cPoWKNNpwBlXlr904UzurndHA93OpYFkbsGny2ZOf0ES/X/4AnwwvLwd1' >> /tmp/proj.b64
          echo 'Gs8iJ6k654OA/dlVMzVKBtZCpYI6hm0PgdMCKc1j7ZuQv/QWlAL/PKS74Dc5WN4VBe7IDcJFYEhl' >> /tmp/proj.b64
          echo 'H5FlsVp0lAxJz4G5hPxzHrGcxzR0XVv+gzqsRhJ3f46DyJ5ThfeOBPFs5UE+QKdeHxFqH8Fa5BXg' >> /tmp/proj.b64
          echo 'xzk2MbmaV0GYUZ7vjn3ZkzPxkYdWaMAg2S8enGwxeqiUo/4TQbw9QUaV6LRYoTsDSvFBrJ1x+EEw' >> /tmp/proj.b64
          echo 'UFFZ5pzdFdbia1/WAsYOWT/UTqMg0fKCrQKu4dNjofrftotBYiccRmHk4x1KtT1u6vWlEICFx8xf' >> /tmp/proj.b64
          echo 'gTmEhSktFePaIKGYlGJJY/Xa1hU9DaJh4olrIx5H4mmIl5fizpFrtaWs26RY5aGeQ0JCQ7FbqEiA' >> /tmp/proj.b64
          echo 'SwldBSkLKsejYtASOpaRjKcVU2p+g5xpRWt0cqOMxUatQ56vkaAvGD/zbu8gxRAgbd+ki+fRVIvr' >> /tmp/proj.b64
          echo 'lNLQ+d6JEVKvTQr2K8J27g3h+Y3Fov++jTF3Xrq1+VOpLmw2jRmDNz010hRd3lsqJ1Ntp5sRXZxH' >> /tmp/proj.b64
          echo 'XK4xaJrHwwwJsPHsyTm4K5iOiWnBTXRhA09dmT0ry8KKTBeDUXR+IqVbSOJpcdmxiJ9l81T6zyGC' >> /tmp/proj.b64
          echo 'qhzi5YLevkWbm8sn8b7MJLzJlEN51ldkGqE5Qeo2bz4yZmpkETHuE5gyooxKyT0kbtQkzJtXcfcW' >> /tmp/proj.b64
          echo 'b3lcy7hD0aFrCfYsEuwvKJP4WL9lScxnf+qI8Z6G+3Oo7uD0M2N25BoWmGYEX8Vc7hkzGimRZzxR' >> /tmp/proj.b64
          echo 'oNGdFnWtnPFv+h6+tv+vi24f/e1vsrY2nIU4kPEpWRZNm4RivlM1X+b4UJqEAlrXqqX7MDbdBN2H' >> /tmp/proj.b64
          echo 'z+RgxA7qgwfWKxYzErGP/ITwfC10Q8PeZ+PdQ9X8WDM9F7XYMGVzdO9XQTl8Czqeap2LA4UefS4f' >> /tmp/proj.b64
          echo '+h/YfdWcdPjmWXoG3vfxZ+DUJ5L8GVQKjkzHB9DxbH+EVQ2V2MTP22VlNjYLOzZ/MtSteTzTWcNG' >> /tmp/proj.b64
          echo 'Ni8oWVSbZ43KikuXwz1IvHIlT/2bbSpU779RYRWkNRQUF04aBVQ2NMvgEqNxEU8s0Sh36JK1R3bl' >> /tmp/proj.b64
          echo 'ift/2T9B82wBQHfF/zdqyvlfjf37X7XtrbX/dxXpW+N/JFwcrJ+BkxFl1BfMPDmUxVKii8fmBOJt' >> /tmp/proj.b64
          echo '2H3isJve2AlA4vFdg01+xxYXM1wQ9WdBiKedCT1yA0kfnvmYK/7T5EJ9UPyV7+6UPI32yQcMH7zf' >> /tmp/proj.b64
          echo 'GDo/cmiIz7x4ohLzGn9vsqwsifMfEaT1PG08JP5Db7D7f/r6/dfVpDT9s0F6T9PGcvnf0LeV9784' >> /tmp/proj.b64
          echo '/bfq1fX73ytJqfM/4maDP5aeCD5QVwwMh1DQSub70SGmsgJgG+OBR8xL6JT6sahC8obOYGI4YIX6' >> /tmp/proj.b64
          echo 'lXzWospXZMj/cdxK/CsLqmlLT9YXQOZjsNKA11xxVnwDygb8K3PumgQspuNpR5GdC6dVghuXxtIy' >> /tmp/proj.b64
          echo 'BDsJ9B6CP5DF7Xl+jpOUilx2Asv7lC1M9yyFODkrzpyl8knMHqiK41R+gqyGGw0CEVqi5qrQPcok' >> /tmp/proj.b64
          echo 'Z4xHkOAVgFZyxZkrO+YbkCA+LQKoeL/GC9XNab6U7hzVXBn3JE/soIzFPNG98U7i/GahM4wrAODX' >> /tmp/proj.b64
          echo '35KDN37yRX0WIjIZzdzIR96EthO6dHgWErMlMGyqtZNzTophM3+wPHB9eoYGpbko4NxZ8mA4TsGJ' >> /tmp/proj.b64
          echo 'MOQ8nGn4VgpSBPzmeI1ZjASMQMlcfIfL2VPJF7vK9Gj6/fIPt+noJm2qBCT1iWPirufCnvW/aBRZ' >> /tmp/proj.b64
          echo 'Ff2IdPjzdVOg4/OmqSeWShOyUeEnT55tC5I4I9jRe/GJdpJNCcWPXooDGVKWPZvke/252FP7fm4R' >> /tmp/proj.b64
          echo '/yo26gmcZot34V7li4byecJlZX3TWFpXOgrwMiDhRJoDwif3ExkRzubBHBhg49CdVxDwR8J4yW/y' >> /tmp/proj.b64
          echo 'qKKYCQTLzb88LRaETR04AccUFUct9Qq+nEIB9eML14z0hsTOi6LqEWQ15DLVDGdWLN4waXijxKdQ' >> /tmp/proj.b64
          echo '36KlfJcyLvi4umUV0+cHykL/4TaGs7EzDidfxdouBiU0YoPhI3y5qfjdxa+v0l0jTrOyk0EPw+hc' >> /tmp/proj.b64
          echo 'kEdNRtxBH09hPX+aYB8gLDYfVmY+iDpQFnUoK5OgO/XCGfWFq0K3lJJ6MlfTtHi4iweZOWPiI30l' >> /tmp/proj.b64
          echo 'QhASbx29zBH7Pw/ApnHHCdwi3NnzGYrcvXzUNMbjdC/RW7TZkf60l6iPbfiFridGSAU9C/FBQ2y7' >> /tmp/proj.b64
          echo '1+j//ud/N1ErhqaXJUcGsbGloQv69tiYennuMVfqwQJbHsxX+4jRLNKNkme4ckw8qSxXUY06DwjO' >> /tmp/proj.b64
          echo 'LYhDGBz0QPRUhOGAjWMrK2DxMM+SBorew8dH7R2lj97i6VTOxWhbj5rKBTZIZvWZNgCpp2/KpKnd' >> /tmp/proj.b64
          echo '0bhlRBnJxyJ3LoekxGscmSvvDNO1q3bsy5c0zdNj+xiby9xwxkUr4hktpG9JH/y88WdGrzJMzsJa' >> /tmp/proj.b64
          echo 'Nh/zxAh7PDVtMSWSRc5EbBpkQoey+meeGLlX0Jkyo/MZg6I+dq3/b+/ae9tGjvj//hQM0ELSRWH1' >> /tmp/proj.b64
          echo 'tqHe9WA7SRvgcne1jbsCB1egpU1EhBIFkfIjRb5JP10/SWdmd8l9SpRs54qCa8CSlsvlPufxm9lh' >> /tmp/proj.b64
          echo 'lJyleZ4uLueM5dJGKc60jeUXyUBvzHNjJIjJq0BBVsVJpwssxdCcmUcYAPMsXc9ACi7W0Q39vohm' >> /tmp/proj.b64
          echo '8QbPfSm/QpIKplHSzNPVOBCZ03g93SQw9r1Bq2WdsaJzeXhaDm0HsJ8uow/sFJSK8nkwvslsHPwc' >> /tmp/proj.b64
          echo 'UXBC9RDZimfJhr8BrebdEhZNRmfbfri6OINntoNurx3gJzxfPb0m6oXx2CyWarX8deyn97DS4s8w' >> /tmp/proj.b64
          echo 'LO+VXyBFLttaWapmzWDh/qblBxh/N4db1bGTCTS2fD4OBp12MGd4cA6+t61SM9iPclecpfevi592' >> /tmp/proj.b64
          echo 'heKcnzjhhwE82AM6gM7Ycadj17x1FssJa9l3WllWhkBUEbiFRjdl/3odq+TuARqdlAME3x83QmKV' >> /tmp/proj.b64
          echo 'Q7lL/Eb9TJhrcMRYCgWI4lT8BDo/vresE3ZdwyIHVA5liNZEvZq27FSlYS3WJx/Od/DRxH9ZSAre' >> /tmp/proj.b64
          echo 'RMREaAfmQzJas337IVUnqjuwSuLRSntES5plN56irjqPae5eu3fzOIeOUCBb6kz3mP/6VbTwbfE9' >> /tmp/proj.b64
          echo 'vIPlfXBPq3a0cRdBB5BDCv6IQVHJyo0qN8U3yRp7jYG9WbX+9g/fZSdWyQvQft2Ly0m1ML25X0XI' >> /tmp/proj.b64
          echo 'A1xzVSzMnzYYnAMevwEu5NxwmFDGAumI3GJMJwo1/Rjdxh8j0O1wjJryaPafveUlG97tsGCnL679' >> /tmp/proj.b64
          echo 'i0nMmN6zkHLfAkfx9RFujGcF/+QE4BJyjGlesxmeSlvmTvrBk5+lZQ+LBQNhYdqUXNa5VZU2cXK3' >> /tmp/proj.b64
          echo 'i527UhXmAGTQ+3DvBbF0aJs1gFrjMDt2jtKJveiI9ij32PspyQgoiafhzmxnprEtBcX3sIxK2+xN' >> /tmp/proj.b64
          echo 'wm7RefL33WaWT1yFbeZTYBxPMbRDXQ10lDcxU2/BUsq/YNHsQWg5qCyqmIGdvhxMPPT5qkI8bNlc' >> /tmp/proj.b64
          echo '8PKaSgCVOKWV91WIhCJ4+ESNRxKI6x18XbvuCoKhx544MiFjlEl+RuTUQIpJPRdbWXPMMh1LJ9kS' >> /tmp/proj.b64
          echo 'VmOz8TZew8LKTLMCyj1SBoKtFAkZ8EXpNK8qqhx35GaWeIEbmyPW0iSHH2RoKaeJh+0fc/vLJf0I' >> /tmp/proj.b64
          echo 'P+KrD9YgIZE97++bKKE3Ch9LmAA7R9XLzsg2KI8vvQ65R61sCsJHeHO4ivI5uj9Gs9OM+y5uAyG2' >> /tmp/proj.b64
          echo '0Cs3CuEiWBoEQa4vAaHeOuagdCL9VA5hYaCQrpaO6X3R5r1VxsmDKFTo44v0k9lFJUfpH8GV3bAT' >> /tmp/proj.b64
          echo 'jF1d5WAmrVGUoHMdsgv+82+OX+KA+JHLL9717/SPNIZMlqkMMlUDlLYhnIctij2MevZReLGTBb60' >> /tmp/proj.b64
          echo 'yD7K7l2KUELvUV4ANrMO0w+FJBAiuHSJd55B54ovKrq0zAVphjrb22ivptCUgM9WJOqGzUFCwWz5' >> /tmp/proj.b64
          echo '7DORE35I0gijkxqglYdz7cucMO59vHRwVHILlnGPWuUgW7bKWZyt0owp4QeErQ9DEpjYob4EyaZZ' >> /tmp/proj.b64
          echo '3O98xL5hrOQsN73DflOM5E06A3r6NMhbKYDM03X8GRGexAJ/tkBvfsW0Oq40mTMMUdmsjHiMrJKF' >> /tmp/proj.b64
          echo 'aC6aOsExatrsf0LGF1SxD8bB9uf5Yi0U3dRnXtH3JY55msQflwvaue/NrDBbRVN2xvI7xgpo0zUL' >> /tmp/proj.b64
          echo 'Yram6zTLjErPrTwOj7c908klO0c4NZn2keimO4Tmkgz1eu6rLmHvxAWbJowCtyIUiIv/VSccWgKd' >> /tmp/proj.b64
          echo 'NrvU0YkfKNsLIuJ4LqipGlakCdjXyvfdJhmlMX9lGfLR1yxnGJFAH+V0eRWtxgV3deDfYz+Wuy+p' >> /tmp/proj.b64
          echo '6A7aQam72HDWHpCvBQFUQXIrAeM2zdkGAHsb0B/aFMWmI3yAcVtvQ+0snBhna7Lm3LHth0M4Xuwg' >> /tmp/proj.b64
          echo 'gT4wY+goKTY0PNGjqFVe6AZQY8sPMl0bOS0nGb320U5Oz1X1SJPfcK/QUR9JVYvLv8SsiJUkrul8' >> /tmp/proj.b64
          echo 'zDVJJjvBAM2wVeTUohcfb1gTaCi+xQs6rbk9qP03QWohMqr9R4GAaDEX1ehrOKWHqsWqk1mHomys' >> /tmp/proj.b64
          echo '5WNYF+qUDUrLTTdU10wrFE6fzVb4AQjau6Vi/O13OuEi08JX7mbZhuPIj2lOviMtKauj3tc0yr/Q' >> /tmp/proj.b64
          echo 'hlfprUPa2UbE0mXywM2daGa8IYusTbaUPWwMbCUWbc+cb6Hpw6ZQg8JB1SQF3PggqIBrb7upgIte' >> /tmp/proj.b64
          echo 'KGyd/FJQBECxmA6LwfA9ljZYdhIHuHT9KKqgrhddqjL2+D5C0Ba6wEeMvx/WGJ0DRCCnrLBFHup6' >> /tmp/proj.b64
          echo 'rnrAr53yUDfUJsSzddW9EYZhsXEX0Uru4nPQCKtOFpZVYkUEM2viDMHEq+nRVrZ38OMEGEXGqCC5' >> /tmp/proj.b64
          echo 'TB0qcUWgVQV5d9qiDdrdczhm7BA7nPKeoA19xWrf16z2FYW3Kpb67TZ6975X+nWYWb2rLl7/UneZ' >> /tmp/proj.b64
          echo 'fVzGHl0PfgrNSpCUGUU/e6xZfk983NRMLKGNUzvQJRRT+pPazbv6E6/dk+W3qOlWNPTuK6zMZkAU' >> /tmp/proj.b64
          echo 'zZPXIVNVMwNVM/08rQr1BLiZZQdZxCDSbRZ8GshP6jNbp3qZPFpdAellufSq4ieGrtRsYFsgKHz6' >> /tmp/proj.b64
          echo 'dR2tdm1gvpjOPavoaf1PepWNQiXXkqiNIu1mSTxj/2jeMOI/QKWGsI03axT2z/EjC1mUsZ82uUMw' >> /tmp/proj.b64
          echo '7g1JMLaYoK6WCNbHzQXUq+A7AT5/r+watuQ6VlAsuC36zAES6r4Mo9tRHOG6uqTx9CyDPvZmGMQq' >> /tmp/proj.b64
          echo 'tOrkuHL+McUXAEz4Yycp9yAJxuIiGiOMXUgra9jzt9AHC2o3FKsLSFcSPQDdmnLCJdpGcXuhQqBg' >> /tmp/proj.b64
          echo 'KxaBVGvcvk5z3ftW3oirLcClX1Eh0xyPLA1VVNqQgVpgNSxWID2y0uJzpajfaAF7Mj1V3cm9TlVP' >> /tmp/proj.b64
          echo 'sv3kWI7z2Xr445zAKoy6KvWdJ/HqAum5OihV6PmJa73/ECPvkw7y75YzfI+TiQzSS8HHpSXL4gp/' >> /tmp/proj.b64
          echo 'Kza1fslifOZ7IHqn+GewGXqcuOE0uYseMoScVmx2SrsAiQINqm8zHzCpSkWNP/yrWdrsvkFC1Qrz' >> /tmp/proj.b64
          echo 'lFvYTrO38T1Id53Wlz8+bu3yzb9VEVOXycjdP46JEIIFu0kVET097+savSG/xBb1s2Slbc4+Tvtn' >> /tmp/proj.b64
          echo 'cXH72RBRyO/y88VYJdhWh4APQpRTjMeURDcsGZcAxpoF71OHXeKZJWhzbi14eE8fo6qeRfsKmP2R' >> /tmp/proj.b64
          echo 'puLa/kVPIGMOzL77NnWB+HiBgtJGZ1vKbFGFFz/LFcUwTycJ4mfrB8nZYSlxJ4ZGW/G6KZVntz5Y' >> /tmp/proj.b64
          echo 'MhjzIbB+YDwns3V8yyboUKw+CJ1UtKUolBPhq3NuO+SABLjOQEnM52wpzodF5KfcaB3exhVbZ+lS' >> /tmp/proj.b64
          echo 'NqxNh8zyyBC+D2vaVNQkW3ftmUTZGDyeRvu8OEBDO7gd/ALKuzz1ye1Wxpybarjgdl77l7B90YfC' >> /tmp/proj.b64
          echo 'PbYYvR7lnFdR2nXjRJgq7S0TvN1punIB/h1jh26x8PuwCqLOfBrdeEvPbKmHeZm4NRFyviSeg4KP' >> /tmp/proj.b64
          echo 'OlXVw6HpM+jEJHQL/9cOPcTjv8iQEs/zjL3e/zQS8X/q9z9+laTPvxVS5EmesSP+26A/GhrzP6T3' >> /tmp/proj.b64
          echo 'f9bxf54/VY3pI4K4KNbqbZFlOAZFoU+kTRvJmzhjqli8y4gz5hs85H3eSDRKNa5QNMplRywa86oR' >> /tmp/proj.b64
          echo 'jEarGzlfcEVey6AR38Z4wAdLvY/v4yV1N8EaKHRLoYuidLBO0XeZvxBB/MgeG+pEqQqUIXxm+JGB' >> /tmp/proj.b64
          echo 'EIJl+u2gGVPvHc2Q/O0W4agxjXFhmyoAID5Br8Xvpho1BfGTAiSRkdfxzHQTX80Vk2YGH98Gffh4' >> /tmp/proj.b64
          echo '+bJUA7mTbjhjSfQAopen8hh06tEQ6g+s4BqF17La+d/i6wLWss6rH1V106T238L+n+KLvtX6W8FU' >> /tmp/proj.b64
          echo 'd8p8Jk9NKcyILshTor0CMinQnjJLyFewMEDMLoYqKiFav/OAWxhDS6zSd7LGNqf5OlEWEyqcdFpb' >> /tmp/proj.b64
          echo 'F5QiudJg8cANhmhZnu8GTWliQwOcTtzC4sGbQ4J4TOWfl0GREIqNQPQMXsId3wTdkXX6R3jKcykV' >> /tmp/proj.b64
          echo 'SgtGJklJ8H2AQX6DV8FtCyrohCdD9FMPOydmRT7zcZnERGGzbClTzpn76jOdW3bI8dtEWhNzE8Gd' >> /tmp/proj.b64
          echo 'nLdg0hQAMcQhUNPFCtWBNjr9+w7ISO3SdpjE5LjJ9oszQB9N9dBK46uEaM0HfKSUS57ZLE+ba9m+' >> /tmp/proj.b64
          echo 'k+eVZ6/azG2fjd0+i37tzVOl9yS622vJtnwEjm3FMYK7+EM8yRko96SVS/uHblzfq/8WtCTOt+8J' >> /tmp/proj.b64
          echo 'Dv2+Ktb/dAr/tNrcZCs2DR+iRfI8z9gV//n4eCDlf/g35PGf6/ifXyXxt+mIkJOIsh3NWPEi1XEA' >> /tmp/proj.b64
          echo 'Au99vADq8+omykA0RxixeEUeMNKs8Peje2EtgUw3n+TpOGgsYds3jkA2ynhonxD4xMsuvpDvNl6n' >> /tmp/proj.b64
          echo 'XFSBDZnNPkHhv3zXx+vBtwP8aBxBM1YgkLPlNGYZFhOKyZiLYniPyIEM+z2E4+CfVB/Wr7ybFrIH' >> /tmp/proj.b64
          echo 'ItsO9AkXu11xVY0eivmQfYw3RfkcjRGkBEB+L+yGXchXo5NC9giyO2WbZaBTenqfrhQemVT5STjA' >> /tmp/proj.b64
          echo 'Dt9OPJ0Goprlzp7LAknMn8w7faQM1iZj2Supzb2CySXHYDy0WJPBOtWpTnWqU53qVKc61alOdapT' >> /tmp/proj.b64
          echo 'nepUpzrV6f88/Rf0rYC+APAAAA==' >> /tmp/proj.b64
          base64 -d /tmp/proj.b64 | tar -xzf -
          echo "Project extracted ok"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: stable
          cache: true

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ShakeShare-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
