name: Build ShakeShare APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Restore project files
        run: |
          rm -f /tmp/proj.b64
          echo 'H4sIAAAAAAAAA+w9a4wjyVmzdyHcDXfJ6hRBQKDUWsuNJzduu23PeOMZz67H49l1Mq8be2+Ph+Tr' >> /tmp/proj.b64
          echo '6S7btdPu7nS1Z8b7gNuISAn84Ih4CZIgBPwCkYsiJP4kOuCEkJAgRBdASKCEHxFPgYh04vGHr6qr' >> /tmp/proj.b64
          echo 'H37M2LMz492761rtuLvqq6++qu+r7/vq0VVScurcQwpCbn6e/0Lo/+XP8rycy+ZkOTefhfhcLj0/' >> /tmp/proj.b64
          echo 'hebPn7SpqQ51FBuhKds0nePgRqW/Q4OUVE0Nt5UmUaWu0tbPowzG4IVs9ij+y6mMHOK/PJWS0/Ny' >> /tmp/proj.b64
          echo 'dgqlzoOY/vAe5/+Bae81dPOA5qcRUgzNNomWsLGOFYpZFEKG0sZ5VG0pexj+2BgVtz+BVjpE13hy' >> /tmp/proj.b64
          echo 'Wzms77K3utaxFYeYRh4tpHgSNvaJbRptbDguKoQaesdxsJ1H0Oq7Ohaxt5V9JY/kHH+lqk0sh3o5' >> /tmp/proj.b64
          echo 'EoKA69hBa25uZCnqntLEVIB4efIeemR1dlETO30oONFIVI5V48j8vEJIsfZQwmsMeDLMhGNjnKCs' >> /tmp/proj.b64
          echo 'LRJENQ2XAsV2SENRwzRzBEnFspJmx7E6Dk0K1AlAyuI9tBK881xAsk5oixhNDwv0SqLnfRptrBKL' >> /tmp/proj.b64
          echo 'QFvSII4V1TU7doLDXsOHStvSsaSabR/EMIG4bjgL7agqpjSPHLuDQ/ENQNGxsYh/1IIZhYkEKSk1' >> /tmp/proj.b64
          echo 'iUOahmnj8ypjhP5PpdPZXvsPP3Im0v+TCJIG2qvumKaenJY8HWXpnSYB5dYfkdCwhQ0NGyoB5SuB' >> /tmp/proj.b64
          echo 'ykqoitrCSf6cnHa13vRHJdLWpyWiYQVS9inzMJLTwrgkdVNVdMmyTQuD3gQ8XoLUtBVNB8hH3Sbv' >> /tmp/proj.b64
          echo 'pSAlveY/vzJO5P8vLLD+n5lPRf7/JELAf955RR882zJG6f9ULhPifwb4n1lIR/7/REIyiWqmldDx' >> /tmp/proj.b64
          echo 'PtaF29sg4EKikmk0SFO49IgYiGLHAe+UChGRIjX9bghB/2eDlfMp40T6P8f8v7SczkX6fxKhl//n' >> /tmp/proj.b64
          echo 'YwNG6P90Kr0g+J9eyMlp4H82m4r0/0SC8OzRXT4RQDQUU822JGRCApnQicpNQMwH2DMdnRgJARPE' >> /tmp/proj.b64
          echo 'a3jfGzD4AwdXlMT4ITZ933P2RXlQlgXWpqrtvYRtygxNJhtO2LJY0R51fPLC7NgqLkEyULVLdOJ0' >> /tmp/proj.b64
          echo '0ceVfUXkl14q71QrW5t1uX7FzwMMbmJn/Dz3+V+3mj4F6PZ+u8YRoQKKydKVmIBzKapihwG1FWJI' >> /tmp/proj.b64
          echo 'bDpLora6SmyKXgBoeE6ylKSL08up4YbS0R3X0obqGGr1imAIn3KibPqN8STmg7aJEWq8tNxX58GG' >> /tmp/proj.b64
          echo 'ZWHfjSrBsAzJ/bGbShuz+qWkVKgYIJOs4sOywWbttGDmyK0IVxu1roXDnPLmze6GppigtUjTAC9C' >> /tmp/proj.b64
          echo '1LnnjUoa3u00e8ChfqTR9YptKDrFvehaNjH2drDLBNoHcT9EoztnCIUNyhQ+VPUOtEVso1wrJiqb' >> /tmp/proj.b64
          echo 'a8nV8nZ5c7W8WaqUq7Fj4NYrpfJmtXwcyOZWDYBigpL7094U410hOCgmSUlJYjIRHl17HZLN57EJ' >> /tmp/proj.b64
          echo 'VNcNi5l2U7qNnV0bpIlKrjjlRYekjqaT3cRtbS+XB/n0+NePQvTAQ4kzVcOHef8hDVyXWS991Fop' >> /tmp/proj.b64
          echo 'CpMKvfafKaqzL+NE/l8mx/y/nByt/00kDPKfG6ozLWNc/s+z2R8GB+P/7ELE/0mEI/jvmpQzEoOT' >> /tmp/proj.b64
          echo '9/95OStH/J9EOJ7/4HqegQw8BP9zcjT+n0gYzf9g6PGwonBi/qdTqUxk/ycSTsT/h5wiPAH/0yk2' >> /tmp/proj.b64
          echo '/5NOLaSi9Z+JhBPzfwOSi6pD9onTlfbGahLG4OPWf+Rg/UfwPzOfTUfzf5MIYisVGpxkmp4mbcu0' >> /tmp/proj.b64
          echo 'HURMf1oPt3exphGj6c8Qii1ZnkRMT6u6QikKS0ke9QHFZ9HdaJLh8QhH9H8b07MbA558/JfNZiL/' >> /tmp/proj.b64
          echo 'byLhGP63idVWrERLs8jpZOHk/F9g5iLi/wTCmPwnal1XOobaAiNgGc2TlTHK/qezC738T8sLmVRk' >> /tmp/proj.b64
          echo '/ycRPru9ef3Z6R9ixvjZyo3VHfi9wf4/9QT8/bufv3wRftqV1WLt8PP//pfFZ6fQxTderz548a3v' >> /tmp/proj.b64
          echo 'lt7/gyR94V8//9Wv6V/8yKsPHvzok7/7PS993+99/8uJ13/8lT944/aDbz7xMBGdC6nYz5a++NNf' >> /tmp/proj.b64
          echo '/QlGXaW8ufr7K6986hE20Ls8HNP/9xW9cyZuwInGf+mUO/+TifT/JMJo/lPH5tu+Dh/646CR47+F' >> /tmp/proj.b64
          echo '8Pif6f8U3/8T6f/zD0tXga/e2n+BrfvHEDZUkw3yCrGO00hciV1dnl6yvSX2Zb6ovORKBf+wphAD' >> /tmp/proj.b64
          echo '0amzp9hy8JnQkhAcyJsMZX7U9Y1Cbxin/3d1fJruP7L/L8jpPv2fy81H/X8i4eH7P0iF6P7rfGRQ' >> /tmp/proj.b64
          echo 'a2HQAMiCvm84hdg1IVd5DpnkqdKKrqh70qZZI46OVxQ7tuzvnFkiDm57+kRkPSCGZh6sQJ6mbXYM' >> /tmp/proj.b64
          echo 'LbbsY1VN3bSTuwzfUpJlFXS54jqEyE3Tbiv640XkY6AZR4//Dg9POwNw8vF/jn0SFvl/Ewhj8/8U' >> /tmp/proj.b64
          echo 'MwAj9X+mf/yfTkff/00mDBn/v8b+8/F/63LnP6amLmAx/v+rP3qaj/9//Y/LX/iH38j89+dW0JMf' >> /tmp/proj.b64
          echo 'yjeTK9+5e2HrmZ+T5/709Q//yW708DAP33nimczszPt/5ymZcWVy8x7j9P/TGoCH0P9ZOdL/Ewnj' >> /tmp/proj.b64
          echo '8//hDcAI/S+nsul+/Z/JRfp/ImGI/n+D/ef6/++/9n/boP//Wej/b3wZ9P/UG6kv/eeLXzr47vcu' >> /tmp/proj.b64
          echo 'fubin134kfzbv2a1l5Lf2nt/TL742Qc3nlndRc89+Qsf/syb1y5HUe+sqB/+8/+a+8OlX63xzh3N' >> /tmp/proj.b64
          echo 'vb8Xwhj6/9QLwA9h/1OZyP5PJIzL/9MsAI8a/2Uy8/32PyVH838TCUPs/yvsP7f/7f/9lgk/vy3s' >> /tmp/proj.b64
          echo '/9dlvv77xq0HL771lW+/+ksf+JXaNUrf/sZv/c9PXfzgRXTt1alPP/m+p+Dh21MXnnjfU9tXIObC' >> /tmp/proj.b64
          echo 'Ex/6wPkn/VPzB5b++hMvzMpvvckqFZmuscPo/t9+JPt/5qPvPyYSxuT/ue7/8fb/9uz/ib7/n0gY' >> /tmp/proj.b64
          echo 'ov9Zs6e4/v/bV4yvw8+K0P9/wfX/1Jdd/f8ptbVz4Qtf+Ztbz3/kqaeffvqbT166dOk376DLly/X' >> /tmp/proj.b64
          echo 'PvgzEP7lwWuvvbZduPjcc3f+7Ylfvvm5N9/+tEVZkZF2fozCEf2/6EZuKAZpYOqcZvV3ZP+fl+dz' >> /tmp/proj.b64
          echo 'A/N/2cj/m0hYagsWI2CxQfNCGgqxluNY+WSSgspvK9Tf78++CGFHmDID4Z0A4p3HWhh2VMXytLvm' >> /tmp/proj.b64
          echo 'eSmRQCt6BzvQji0U13FTUbuouF1BSygjz6JEQiyOdiimCQvbbUL5wRXeYmrPqqsUAEgr6zfLta2t' >> /tmp/proj.b64
          echo '2o3gGAYvT1s5DI7AKMQyqRhKnrqYenF1o7I5bmFDa8+qnZFfOJNa16ul4hBqGMJtH3xNV5q0EDPw' >> /tmp/proj.b64
          echo 'PrbXTHvdFIe6nE1zvFTeqVWq5TPBVtra3CyXan1td4uskVM0VrFUKler9VuVtUq9WivWTkNq6UZx' >> /tmp/proj.b64
          echo '83r5bHBtlos7Kz/m4lotv1QphY8bOTkng/byolHcxp/sEJsdnmLaaBMr9m6Xne1mYJUfg3IaERSt' >> /tmp/proj.b64
          echo 'ulbZLNfXt0rFWmVr8xSNIdCVtoo71T6EQcWqjmmz75WSaANrRDkF9Tvl4mq9/HKtvLNZXAdObu0U' >> /tmp/proj.b64
          echo 'r5dH9+r0KWp4a6dSK5+8zPSVU5TJq7lRXq0U65UNKK0aatDQQUMDNOjKLtYLsWBDX8xPYidfF2LX' >> /tmp/proj.b64
          echo '3PFBeGgwWBOXrMt3QyWxA4bu+5ADOZi8gjla5/ahfOhg21B0wfVCjB08FN6Po3jfnaFQ6C1cCn+L' >> /tmp/proj.b64
          echo 'FhsKiA/Zh25YE/iHwrh13DA1QEmJ0dRxzbSGgzpsGxE0kLupKLw7aii4yk8/KrUUo4mhZ5s28Q7r' >> /tmp/proj.b64
          echo 'ubeHu7umYms3iKbh4PUeVW2MjSq5g+/RtqLr0GDVIIqfsAs/StfsOKvQ+XlXv9cwDYBiKW72dZ5+' >> /tmp/proj.b64
          echo 'DxBTaJl7HcIqN5xE4L92ADJQVFWsY1sZ0Vbulqiq2XAqhtVx3EZTtNvga+1gCiSGWMjZ2MaOktAU' >> /tmp/proj.b64
          echo 'R+mJHuTlsZ8ihnd4HYnH23Dls6dnX1iyjy5iOMCLRIPoUOTyAFIufkd2Qjez5MJIG8XK5kABHAl0' >> /tmp/proj.b64
          echo 'C9w07e7xaDwoab14c7N0o7wzSG3yCHKXkl43CcUNb/JeEkRbl72mHs5tvk8UtFSgpJKh7s52uXk+' >> /tmp/proj.b64
          echo 'ZrT997ELwfhPHOsaHMx9ZmWMnP+Rc33nP2dz6Wj9fyKBHSgnOH97v63Y4FsmXm4fZq97JzVK4HGI' >> /tmp/proj.b64
          echo '2YCXC/zcPy8B81P5Po4d0iDYLkS3RrwTQ3//P48jgMed/w+d/7aQitZ/JxIG+H9gg/HG9lnKwYn4' >> /tmp/proj.b64
          echo 'n2P8z6Zz0fkvEwlH8l+c3CteT+UWjLL/Gf/7H3H+c1rOyHJk/ycRNMI+09vtMFd9RaG4cH2nuLpe' >> /tmp/proj.b64
          echo 'rt+slnfqN7Y2ytNhiG3FaRU8CWEJdPoOsdjoHA/P7KUOyRjGe9PWC2zCmf4km3LG9j5RsX/RALgo' >> /tmp/proj.b64
          echo 'yTAw9WQzJy1ImQQMfyUoJnI9HioE/b/vfoczLGNE/5cz/v1P/vnvmYX5qP9PIrgns28ohtLkh0SL' >> /tmp/proj.b64
          echo 'c6c13PAuw6tqe6z3okLoxGyWHFgESDLwAdr2I+KzPiS7TCQe67/zKTYrHRCnxWeHqo6NlTa6G0Io' >> /tmp/proj.b64
          echo '6aaixYkzK87uPpKiUJYmdgQB3bg3cSFRbS8W0KJQUC1OP5ZLQH1H1+dQOBe7No/deMIuPhkgPnTE' >> /tmp/proj.b64
          echo 'udOxjT6E7knfogmIwc8D5zcPxmOX7/aC3k96Nxl61wPym7g8BSdIt7FlUuKwecHwqeVN02xC2wbV' >> /tmp/proj.b64
          echo 'ayv72CgBD21FD0W7uLY5n7dN2/ET2Wnkg8f/DzvF34VKMK5gO+Z9LdpzSvxxNwcEGXJSVkrH+AH3' >> /tmp/proj.b64
          echo '3dBZ7SzzsJPNPWw9RbKDzXsw3J8WrYxieX44/qPuU++kICV1snvOdwCfwP9PpzLs++9Udj46/2si' >> /tmp/proj.b64
          echo 'weU/dBt+EeD5lDHK/s8P8D8tp6L9HxMJ4ozHGWGI8kLlJ9sK/CVg95hYzCxO98O51qfO1pTAXIVe' >> /tmp/proj.b64
          echo '+jO4a0002TLbuO6+eCDirMhgibFoWQgfOtjQINYBCnRM6S2isUtXmIViN+46vfDxu7TDxqd7uHt/' >> /tmp/proj.b64
          echo 'dpGta14zwVjYRGOmReTl95PEuREuAY1QBEPFfmeF5ROWfEPUmiEWBtRhpwDk0UxQ6szctOeS7Haa' >> /tmp/proj.b64
          echo '1ZZ5UGphdQ9rbJ1rRTEMdr8xN00eIF8QzCO+yLSqOErcN867Nmm2HINfx7viP7MG2pvzgaiqNBqm' >> /tmp/proj.b64
          echo 'rgVnDJTYwQJ50R78JZ46XFtL8X+zQU5+AEFVdYsvBS9SwzbbVYy1eGhFh8L7EYjXPpbLyAshxGNS' >> /tmp/proj.b64
          echo 'PiupptW9Ba5eT0Edu6GoeLAYucj+hYoJPTJu1dyKXOfitsalzTItCxyGmpca9xuZkxKflfyMIWQd' >> /tmp/proj.b64
          echo 'ij1WZ9z7jr00H4jJq0fhDXh211fjIh1EzXWgHnX/PW1w9b835D4fR2B8+59JpebZ+k+aTQlF9n8C' >> /tmp/proj.b64
          echo 'oY//fPNeXbyelUswyv5n0xmf/xk+/7uQiuz/ZIJnphmr8wrtGmrIdvNI8ARaQxwACkbdtGkdxoYg' >> /tmp/proj.b64
          echo 'NqGXodbdFShubCnb26IKzaqZnV0do7rTsjFtgY2DQb2clVKL/YDEcFAdDC5YPxVvsCmHj6U4lDt9' >> /tmp/proj.b64
          echo 'UO3sgm9B+NVeS2KXCihttnkBBsXO8lVUp51dBg+mAddIG0MM0Odw8rjfsM+upWPC4MT54xqUxNDF' >> /tmp/proj.b64
          echo 'Z5FpcDDPWWCogABloBiXFs/UUaUNY2CjuQ12xtQ8W7IqrlSNt4muE4ohVgMTKqdSnmmRIBp8oHjc' >> /tmp/proj.b64
          echo 'L5BNoxiKDiP8JpRLPwkkYukQfRSxvy/A3y5/7vLnO/z5DrdQfHDdQHGWcTnUyrOheQQXtWEeAGqv' >> /tmp/proj.b64
          echo 'cSR4jfsYXBxBc6GCO2WC7t3r2RACmSSNNBrYxsCkUIZLsxIxNkL1ZcQEzJztuSMuXA5DuRhKE4wI' >> /tmp/proj.b64
          echo 'k+bNEIm73oRhDvhpWvEw365KqgKF6h4KwUtWnXeLST9R6NP/Bt8gesYG4Hj9L8vz87Kn/2V2FiTo' >> /tmp/proj.b64
          echo 'f3lhIdL/kwg9qt7pWlirs01hQxS+EA012DucHIzqU/6rmIlRxWiYvAu6qqbqHh0JozzLBLVe0Rb7' >> /tmp/proj.b64
          echo 'k9jus0V/vBcgid/1dzM7LUKlAMUc6k1hGJguAE2AjU5bbHzmY0p0FxFNx3Mw3lFstQXlzSFRAwx4' >> /tmp/proj.b64
          echo 'HFsxaIONIFmCZhoACW+mzbSKWyuBbNCmuZXoTa4TUC89UVLdVT4wBnLYtr+eRFBWBVCOhAEMydVv' >> /tmp/proj.b64
          echo 'FkWDeR22wuznzOBXGDMD9hQysg2FXcjqPRX8SGk7vc32tu/wAr0yYNBk89tBoYhqNXETXmcW/XSw' >> /tmp/proj.b64
          echo 'p34ruiwNt3md8p9COFJibAhMr29vA37PXgWN776usWHv4gCsW3YIbt2kzlFgcygEXjGgmeBlx91v' >> /tmp/proj.b64
          echo 'PJhn1zR1Dhnslt/BtKMPAXXLJ9RvgEGQmyCmV9bBsLuw0MV2sIrJ/jBY1ynigNu22QSbTQeBQg3J' >> /tmp/proj.b64
          echo 'IfmTu4lY440abn42CSI4sCx4EeYcSw4xjwP1MNM3p9i5KaQgHuqrrsyG5MPrwDwTCKfDyQjTjJjV' >> /tmp/proj.b64
          echo 'D8SCLvZVgdlpXY/T2UXXmieTfEaoQ9mKzKDeQRkpI8mopVBwGdAeuA0GqxU4ZlRycwPdyDFdoqGT' >> /tmp/proj.b64
          echo '/eOrv8i8GuLOBLE1BzTDu/lMcsbGtwEtPDQUos8AzAxFCmIvHehOgI6JBvRRWu2AC0hpXFBG+Y/n' >> /tmp/proj.b64
          echo 'bbjKgHmqbrwUlA6P6+YBtksK9X0ZMQN1iUoeQXFB0Cx6/vneeEHgYAInOHCB1jqAEy8xcpdd17bq' >> /tmp/proj.b64
          echo '6TxoAu7tC2Id0EOeE6YcKNAsLq+AVp6vqO2zxS+28T2YyfE5PhdokdCslaeS8iH1FCSH+1XFIA5h' >> /tmp/proj.b64
          echo 'm8rzKE5ABxPW93ucwoH+KuTDg/ZNASMn7B0OL9DtyKK0XraFHN6AwQJktu8y43pPpwGzstibPEzw' >> /tmp/proj.b64
          echo 'JT/PbC/0IH2ijmx6qgf2PsL6wMXKwwvzbdy4hfF5y97ShjdmWN3xhuzz4nubxvOvj6eWGYSesnuL' >> /tmp/proj.b64
          echo 'ESQOY68fN0x4OQ6Q3+6ZiW5ZSBu3SkKMDI6N7qsVrV92QyZM1CHk0wROTB55ePKuWj1KkL3imbHz' >> /tmp/proj.b64
          echo '2r7HAvq9A129imZmmBIdaKlxBUYoJiaFbtR9pCqO2kLh8elwZFx/9SPiEiYw9SkqZi6WkfgCKBDQ' >> /tmp/proj.b64
          echo '+IDHOLbyGsQ1TARCfmSkn85JP71LNU5PZzi+Gxwh7mwayTobaR9A5ZM9XMK3le66qWjgiRK870u3' >> /tmp/proj.b64
          echo 'pXTZTo9BgRMJ0m7XwdTbN8N8kJ6ESxKhm6ZTbltOt18gez1f0bq9uQekznOBBbQspWbHEWM2chtH' >> /tmp/proj.b64
          echo 'qrbd0mti2HfTguEvFi3R4S+DDeHGgxfnKPoKb4xllOqvq+v/WSCKHjyvoFcQG6om0QCmWQnGmG0r' >> /tmp/proj.b64
          echo 'npJSc2iwrgPNYfUBhMgbKG65MKS8PqrHbs5wgw5t3DPrIK63e8IOMmgI+pCEci8GRNaByH4qhPsM' >> /tmp/proj.b64
          echo 'GXiLDRY/h/zRHWKTJ0f31+HVD085HOnIeMULeY2Hi+eFehmP7TFjMHfi9p7N0RaZlh1/RMIzeF4Q' >> /tmp/proj.b64
          echo 'jR/t/QFgaORyHFzgJPYLricTx5iYEcblMZ5Vdud/2Zkv57cBaNT+/2w6F7r/I8vWf9PR/t/JhIfd' >> /tmp/proj.b64
          echo '/+PB+Zv1++C8HWVsLpjPAjER6+ni7t4cKu6GXSEG/5gbGxQ0g+tw6+QO1tzu6HbYapc6/9/ele42' >> /tmp/proj.b64
          echo 'biTh//MUNJBAUkZDS/IJZZLAdmayA2R2ZsfezAIDr0CJbYswJQok5SOJ/+4L7N99ujzJVvVB9klR' >> /tmp/proj.b64
          echo 'lu0sFmwDltRsNvuorq76qrpIZidTtLkBR8w/poRtbR/KM/NZ+wvTg6Q8H9uUQg1/X5zT6tLlHF18' >> /tmp/proj.b64
          echo 'bP5EHYoa/9nT8myJ23+4k9bTPGMd/8/+Lj3/199p/D+eJanzrzvpPc4zqvn/bn9/MNDmf2+n17z/' >> /tmp/proj.b64
          echo '+1mSYv+LEt35o9IiuOZeMQrmERbd1n5v7GIqboDaLsloEU2uoFHyD9cNZZic0TSYg7SWbptZrpuv' >> /tmp/proj.b64
          echo 'ozHz5NguvulFfb/Ssu4oafpgqQVv2Ma5nQZwbcR+aXbX0mFR9ae9WMaGO63k3FjpS0sreF2W/t6D' >> /tmp/proj.b64
          echo 'D8hici8zAZVXeS61wLI26RfVlikVl7ZizZbKBlE3qHJzKrMgy+5Go4y7kci5cul3SCQfKY14nFag' >> /tmp/proj.b64
          echo 'tJTLba6FwUego1Cq0GvYRVmJM6+ihiXnCr+nBVfV4Br1ZkId8nUJDlM3GUoVUODLeWmzY5azZUZt' >> /tmp/proj.b64
          echo 'sbSTd8ky9RZTfE6eYPdCbibzeA0t+W6WJ6y5LdOwPEpStMPBVcML2LAlj8aXSjnuhmyWmwRpqJTk' >> /tmp/proj.b64
          echo 'Dr8GrVGJMQIhUBAX0wQZeUr5XPtSe3N6+uqr31RPJl92tjqN5hPyZpGAbvc1epH1vJfoftW7b/Hq' >> /tmp/proj.b64
          echo '2Lj5srFTeoR4KIeWy8hsWelTBJrv4gR07zHwCikbJ4qZJNoj4VOmG+uYTmytXdGPmUT8hSu0ZTk/' >> /tmp/proj.b64
          echo '5qHfuualsYhAWHXtdBJU3isUalJViAMtliJscD9HFxEj88xSBsg4T2wXMhYHjF05F+h+W3P6MsZf' >> /tmp/proj.b64
          echo '+H/xiVUMMojPSVgn4mdbM7iAADiHMARqUCj5bRk1o3eIZeoH87t2+5Zyw1vJPwVd5kLptwbVl7eH' >> /tmp/proj.b64
          echo 'YVsF3qWF/tVvRbmYzC/z6T1f2+2s413QzrAebrUkwJp/uxewxrcvrIOBZiMci2ijwSgamJIZrOfP' >> /tmp/proj.b64
          echo 'U5JCiZCOR6iNRyR3lBo0xM1RRtFjhJZlpttRuJ7I9X2/6K67k5p5hvW0y70XSlQLD3MUGOGPINMk' >> /tmp/proj.b64
          echo 'l2U5V926YQMrT642Gsain8mV94PXOhG405Z3SmL45t1MgxwZPXXx8cYkTm68P/7175Y3LErjeUl0' >> /tmp/proj.b64
          echo 'CCCh751heLFLRHlqjJWM0dPlQTHNDXrj2hsFzbDNsUQcaa60NfaZQ7CxIN5C56AFvKUZM4aBjBNL' >> /tmp/proj.b64
          echo 'K8DdzY/lA9qL9fuH8o7UxoV7OCWDEj5ro6F0yCDa6pvEUEg2W0mDJjfHZ5IRElJKeK6VQhT2Wnjh' >> /tmp/proj.b64
          echo 'imPD3BhZNOz339U5V/v2SyEuM8GZtEPuEz30+nsCq7b1X+u9TDCGhFU1HjY2QuOjqhJTyVnESBSi' >> /tmp/proj.b64
          echo 'geZLo+8/NjZiMRvwLEm2kEbUThhY9fskDOLjJM+T2emUkFyY+fiZtqH4IjbQsX5ujApi4ipwkEVx' >> /tmp/proj.b64
          echo '0ukTliJoEcwDjHF5nKQhSMEFHY3p709BGC3x3Jf0y6dSwSSI23myGHo8cxKlk2UMYz/Y7XSMM1b0' >> /tmp/proj.b64
          echo 'XB6elkOMHdbTaXBBjkCpKJ8H4xuHQ+9jQOMPyofIFixLNPwNaDXv5kA0GT3b9vPZp2N4ZtfrD7oe' >> /tmp/proj.b64
          echo 'fsLz5dNrvF4Yj+VsLlfrUaDy6BYoLfoVhuW99AukyHlXKUurSQkQ7hcl38MQu+iTJY+dSKCx5dOh' >> /tmp/proj.b64
          echo 't9vrelOCB+fge9coFcJ6FKviOLn9sfhpVsjP+fETfhjAg9yhA2hIDno9s+bKWSwnrGPeaWQZGRxR' >> /tmp/proj.b64
          echo 'ReAWGt0W/Rv0jJKrB2j/sBwg+L7ZCHEqh3Kn+I32Mya2weFjyRUgGqfiA+j8UX7X7vl927CIARVD' >> /tmp/proj.b64
          echo '6aPVTa2mKzpVa1gL+mTD+Q4+2vgv86mCN+JhEbqe/pCM0uyO+ZC6E9XfNUri0UpzREueZTaeBla1' >> /tmp/proj.b64
          echo 'HtNcTbs30yiHjtBYtbQz/QP26zNv4dviu39z0DPpqm5P63a0dRNAB3CH5Psjxj2l1mBUuWl8k6y1' >> /tmp/proj.b64
          echo '1hiYi1Xp787DV9mhUfITaL924rJyLUxvbhcB7gG2uSoI88MS43PA45ewC1kXHCaUsUA6op4lpqNB' >> /tmp/proj.b64
          echo 'mf4aXEeXAeh2OEZtcTT7W2d5sQ1XGvUdd9/b1i8mPmNqz3ya+xZ2FFcf4cYoLPZPxgBOIUeb5pSE' >> /tmp/proj.b64
          echo 'eCxtnlv5B0vuLS27m80ICAuTtthlrUtVahNjd6u2c1uqszkAG3Q+3HmBkw5dZi3g1jjMlpUjdWIt' >> /tmp/proj.b64
          echo 'PqI8yj72bk6yD5zE0XBrtjVTW5ac4zu2jFrL7E1MrtHv8M9dZoZbWY1l5lJgLE/RtENVDbSU1zFT' >> /tmp/proj.b64
          echo 'Z8FSyv9EgvCOazmoLMqYgZnuH8w81PmqwzxM2Zzv5Q2XAC5xRCnvWZiEJHi4RI0NGcT5in1duW4L' >> /tmp/proj.b64
          echo 'gqHGnnihQ8Yok3xE5FRDiql6zpey4sDEPJhk+GsO1NhuvY1SIKxMNyug3CNkIFhKAZcBt1qax1fp' >> /tmp/proj.b64
          echo '6yXMLNEMFzZDrIVJDj+ooaWcJhaZf8jsL6f0h3+JbzdIQUKi9ry/LYMYBPGhdyBgAuwcrV50RrRB' >> /tmp/proj.b64
          echo 'enzpncc8V0VTED7Cm/1FkE/RRTAIjzLm41cFQlTwKzsKYWNYCgRBXV88inqrmIPUieSqHMLCQCFc' >> /tmp/proj.b64
          echo 'Ei3Tu9VlvZXGyYEo1OjjVnKld1HKkfpH4cq+3/OGtq4yMJPSKErQuQrZeX/8h+GXOCBu5PLeSf9W' >> /tmp/proj.b64
          echo 'P0JtyESZ2iBTPUCpCuF8GFGsYdQzj73zlczxpVl2Kbp3ykMJvUd5AbaZ1E8uCknAR3DpFO88hs4V' >> /tmp/proj.b64
          echo 'X2R0aZ5z1gx1dqt4r6LQlIBPJRI1JlOQUDBbPPuY5/gXcRJgdFINtHLsXOtuThj3PppbdlTqPivi' >> /tmp/proj.b64
          echo 'HnXKQTZslWGULZKMSKEGuK0Pww/o2KFKgtSmWdxvfcS6YazELLedwz4uRnKchMBPHwd5KwWQaZJG' >> /tmp/proj.b64
          echo 'vyLCExvgTwX05lZM6+NKoynBKJXt2ojHvlGyEM15U0c4Rm1z+x9R4wuq2A/Gwdbf8zktFN1UZ17S' >> /tmp/proj.b64
          echo '9wWOeRRHl/MZXbnv9Sw/WwQTckzyG0IKaNM2C3y2JmmSZVqlJ0Yeg8e7julkkp0lnJpI60h0kxVC' >> /tmp/proj.b64
          echo 'c8mGBgP7VZuwd2iDTWN6nPgUoUAk/lc9f88Q6JTZpR0duYGytSAihueCmqpgRYqAfS59X22SkRrz' >> /tmp/proj.b64
          echo 'E8lwH/2R5AQjEqijnMzPgsWw2F0t+PfQjeWuyyr6u12v1F1MOGsNyNeAAOogubWAcZPnVAHAzgbs' >> /tmp/proj.b64
          echo '7JkcxeQjbIBxWVehdgZOjLM1Stnu2HXDIQwvtrBAF5ixZynJFzQ80aGo1SZ0Dagx5QeRzrWcjpWN' >> /tmp/proj.b64
          echo 'nrt4J+PnsnqkyG+4VuiRGMFVi8u/RORGO7Cv7mO2SdK3EwzRDEtFTC168bGGtYGH4ou6oNOK24Pc' >> /tmp/proj.b64
          echo 'fx2k5iKj3H8UCCgvZqIa/epP6EPlYvXZrEVR1mj5AOhCnrLd0nLT92Wa6fjc6bPd8S+Aob2bS8bf' >> /tmp/proj.b64
          echo 'nV7Pn2VK+MrVW7bmOFKePOSZqPe1tfJbyvBKvbVIO1VMLJnHd8zciWbGMbXImmxLWsPawNbaos2Z' >> /tmp/proj.b64
          echo 'cxGaOmwSNygcVHVWwIwPnAvY1radC9j4hbStU78UFAFQLKaHqmD4NuUNhp3EAi6db8QVZHpRpSpt' >> /tmp/proj.b64
          echo 'ja8jBFXwBTZi7BWw2ug8QASyygoV8lDfcdUBfq2Uh/q+MiGOpSuvDd/3i4U7CxZiFZ+ARlh3srCs' >> /tmp/proj.b64
          echo 'FEvBC42J0wQTp6ZHl7K5gjcTYCQZo4bkMrGoxDWBVhnkXWmL1nj3wOKYsULssMp7nDfsSFb7HcVq' >> /tmp/proj.b64
          echo 'X1N4q2Opr7bR29e91K+HmdX7MvG6Sd1m9rEZe1Q9+DE0K85SQhr9bFOz/Jr4uK6ZGEIb43agS0im' >> /tmp/proj.b64
          echo '9Ee1m/fVJ57bJ8ttUVOtaOjdV1iZ9RgiiievRaaqZwaqZ/p5XBXqEXAzww4yi0CkW87YNFA/qV9J' >> /tmp/proj.b64
          echo 'mqhl8mBxBqyX5MKrip0YOpOzYdsCQeHqcxosVi1gRkwnDip6XP+TQW2jULlrFaFcS2k3i6OQ/KM9' >> /tmp/proj.b64
          echo 'JnT/AS61B8t4maKwf4IfmU+CjHxY5hbBeLBHBWNjE1TVEiXuGO2V9x0Hn3+QVg2ZMx3LKwiuQp95' >> /tmp/proj.b64
          echo 'gIS67obR70mOcH1V0nj8LYN+rL1h0K1CqU6MK9s/JvgCgBF77ChhHiTekF9EY4S2Cill7Q3cLXTB' >> /tmp/proj.b64
          echo 'gsoNBXUB64qDO+BbE8a4eNtoeBaoEDjYggQg1Wq3p0muet+KG5HaPCT9mgqZ4nhkaKi80pYIRQLU' >> /tmp/proj.b64
          echo 'MFuA9EhKi8+ZpH6jBezR9FR5JQ96dT3J1pNjGc5n6uGbOYHVGHVZ6juJo8Un5OfyoNTh54c2ev85' >> /tmp/proj.b64
          echo 'wr1POMi/m4f4KicdGaTv/R6WlixjV/hLsajVS8bGN9HeAzE4wj9tm6GP4zccxTfBXYaQ04KER3QV' >> /tmp/proj.b64
          echo 'IFOgg+pazA+YVKmi1le/tUub3Tc0XncR0fEoexvdgnTX69x/vRntssVfqYjJZLJv7x/DRCiCBatJ' >> /tmp/proj.b64
          echo 'FhEdPd9RNXpNfokM7mfISlXOPlb7Z3Gx+mwIL+R2+bnXqATbahHwQYiyivGY4mBM4mEJYKTEe59Y' >> /tmp/proj.b64
          echo '7BJPLEHrc2vAw2v6GNX1LFpXwNzZV1Rc07/oEWTMXb3vrkVdID5OoKC00ZmWMlNUYcWPc0kxzJNR' >> /tmp/proj.b64
          echo 'jPhZeid2diAl5sTQ6kpeN6XybNcHyw1GfwjQD4znKEyjazJCh2L5QeikopAiV064r86J6ZADEmCa' >> /tmp/proj.b64
          echo 'gZKYT8mcnw8LqJ9yq/PwNi5ImiVz0bAuPWSWB5rw/bCmTXhNonXnjkkUjcHjaXSdFwdo6Aruer+A' >> /tmp/proj.b64
          echo '8i5OfTK7lTbnuhrOdzun/YvbvuiHtHtUGL02cs6rKe3acSJMtdaWDt6uNF3ZAP+etkIrLPwurIJy' >> /tmp/proj.b64
          echo 'ZzaNdrxloLfUsXnpuDVl5IwknoKD7/fqqod7us+gFZNQLfzPHXqIxX8RISWe5hnrxP/p7fP4P837' >> /tmp/proj.b64
          echo 'H58lqfNvhBR5lGesiP9GX/aszv8eff9nE//n6VPdmD48iItkra6KLMMwKBr6RNi0kb3xM6aSxbuM' >> /tmp/proj.b64
          echo 'OKO/wUPc54xEI1VjC0UjXbbEotGvasFolLpx5/POqNcyaMTXER7wwVLvo9toTrsbYw00dEuhi6J0' >> /tmp/proj.b64
          echo 'kCbou8zepcB/ZJuGOpGqAmUIn+lfEhBCsMxO12tHtPeWZoj97RrhqCEd48I2VQBAk6pXVA165Tuq' >> /tmp/proj.b64
          echo 'eHPwzHQbX80VUc0MPl57O/Dx8mWpBjInXT8kcXAHopej8gh06v09qN8zgmsUXsty579E5wWsZZxX' >> /tmp/proj.b64
          echo 'f1HXTZO2/xrW/wRfKyHX3/EmqlPmE3lqCmGGd0GcEh0UkEmB9pRZXL4CwgAxuxiqoIRo3c4DdmEM' >> /tmp/proj.b64
          echo 'LbFS36k1tj3J01giJlQ46WltVVAKBKUB8cANmmhZnu8GTWlkQgOMT1wD8eDNPoV4dOWfv0cDBgqK' >> /tmp/proj.b64
          echo '7YPo6b2EO77x+vvG6R/uKc+kVCjNNzLBSrwfPAyG673yrjtQQc8/3EM/db93qFfkMh+XiU8UNsuU' >> /tmp/proj.b64
          echo 'MsWc2a8+0bllixxfJdLqmBsP7mS9BZOiAPAh1mNVOw7ICO3SdJjEZLnJ9IvTQB9F9VBKb29z/yqP' >> /tmp/proj.b64
          echo 'jZR0yTGb5WlzJdt18rz27NWbuerZWO2z6NbeHFU6T6LbvZZMy4dnWVYMI7iJLqJRTkC5p1q5sH+o' >> /tmp/proj.b64
          echo 'xvW1+m9AS/x8+5rg0J+rYv1PJ397sRxnCzLx74JZ/DTPWBX/+eBgV8j/8G+PxX9u4n8+S2Jvm+Eh' >> /tmp/proj.b64
          echo 'JxFlexGS4k2qQw8E3ttoBtzn1TjIQDRHGLF4RR5spFnh70fvBVoCmW46ypOh15rDsm+9ANkoY6F9' >> /tmp/proj.b64
          echo 'fNgnXvbxhXzXUZowUQUWZBZeQeHvv9vB697rXfxovYBmLEAgJ/NJRDIsxhWTIRPF8B6eAxnm+8CG' >> /tmp/proj.b64
          echo '3j9pfVi/9G5ayN7l2WagT7jY7/OrcvRQzIfsA7wpyKdojKBKAOQP/L7fh3w5Oilk70N2r2yzCHRK' >> /tmp/proj.b64
          echo 'n75DrxQembTyQ38XO3w9cnQamGqWW3suCsQRezLr9AtpsJYZyV4Jbe4VTC51DMZDiw0bbFKTmtSk' >> /tmp/proj.b64
          echo 'JjWpSU1qUpOa1KQmNalJTWpSk5rUpCY1qUlNalKT/s/SfwGAds8LABgBAA==' >> /tmp/proj.b64
          base64 -d /tmp/proj.b64 | tar -xzf -

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: stable
          cache: true

      - name: Get packages
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug --no-tree-shake-icons

      - name: Find APK
        run: find . -name "*.apk" 2>/dev/null

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ShakeShare-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7
